name: bimap-p2
channels:
  - conda-forge
  - pytorch

dependencies:
  # --- Core runtime ---
  - python=3.10
  - pip
  - tk                          # for Tk-based file dialogs in your scripts

  # --- Numerics / image / plotting ---
  - numpy=1.26.*
  - scipy=1.11.*
  - scikit-image=0.23.*
  - pandas=2.2.*
  - matplotlib=3.8.*
  - opencv=4.9.*               # conda-forge OpenCV build
  - tifffile>=2024.5.10

  # --- PyTorch (CPU build) ---
  - pytorch=2.2.*
  - torchvision=0.17.*
  - cpuonly                    # ensure a CPU-only PyTorch

  # --- Utilities used by your scripts ---
  - libsvm                     # for BRISQUE backend (your code has shims)
  - openpyxl                   # Excel writer (path A)
  - xlsxwriter                 # Excel writer (path B)

  # --- PyPI packages (install via pip from within the conda env) ---
  - pip:
      # Microscopy + denoising
      - cellpose==3.0.7
      - csbdeep==0.7.4
      - n2v==0.3.4
      - czifile==2019.7.2
      - read-roi==1.6.1

      # Image quality metrics
      - brisque==0.0.16

      # TensorFlow backend for N2V / CSBDeep (CPU)
      - tensorflow==2.12.*
      - keras==2.12.*
      - tensorflow-io-gcs-filesystem==0.31.0

      # If running headless, you can swap OpenCV:
      # - opencv-python-headless==4.9.0.80
